package objects.administration;

import java.io.File;
import java.io.FileInputStream;
import java.util.Properties;

import statics.Const;

public enum AnimationNames {

	MAGE1_IDLE, MAGE1_WALKING, MAGE1_ATTACK, MAGE1_ATTACK2, MAGE1_SPECIAL_ATTACK, MAGE1_THROW, MAGE1_CAST, MAGE1_EMOTE, MAGE2_IDLE, MAGE2_WALKING, MAGE2_ATTACK, MAGE2_ATTACK2, MAGE2_SPECIAL_ATTACK, MAGE2_THROW, MAGE2_CAST, MAGE2_EMOTE, MAGE3_IDLE, MAGE3_WALKING, MAGE3_ATTACK, MAGE3_ATTACK2, MAGE3_SPECIAL_ATTACK, MAGE3_THROW, MAGE3_CAST, MAGE3_EMOTE, TROLL_IDLE, TROLL_WALKING, TROLL_ATTACK, TROLL_ATTACK2, TROLL_SPECIAL_ATTACK, TROLL_THROW, GOBLIN_IDLE, GOBLIN_WALKING, GOBLIN_ATTACK, GOBLIN_ATTACK2, GOBLIN_EMOTE, FIRE_ELEMENTAL_IDLE, FIRE_ELEMENTAL_WALKING, FIRE_ELEMENTAL_ATTACK, FIRE_ELEMENTAL_ATTACK2, FIRE_ELEMENTAL_SPECIAL_ATTACK, FIRE_ELEMENTAL_CAST, AIR_ELEMENTAL_IDLE, AIR_ELEMENTAL_WALKING, AIR_ELEMENTAL_ATTACK, AIR_ELEMENTAL_ATTACK2, AIR_ELEMENTAL_SPECIAL_ATTACK, AIR_ELEMENTAL_CAST, EARTH_ELEMENTAL_IDLE, EARTH_ELEMENTAL_WALKING, EARTH_ELEMENTAL_ATTACK, EARTH_ELEMENTAL_ATTACK2, EARTH_ELEMENTAL_SPECIAL_ATTACK, EARTH_ELEMENTAL_CAST, WATER_ELEMENTAL_IDLE, WATER_ELEMENTAL_WALKING, WATER_ELEMENTAL_ATTACK, WATER_ELEMENTAL_ATTACK2, WATER_ELEMENTAL_SPECIAL_ATTACK, WATER_ELEMENTAL_CAST, SKELETON_IDLE, SKELETON_WALKING, SKELETON_ATTACK, SKELETON_ATTACK2, SKELETON_SPECIAL_ATTACK, SNAKE_PERSON_IDLE, SNAKE_PERSON_WALKING, SNAKE_PERSON_ATTACK, FISH_FROG_MAN_IDLE, FISH_FROG_MAN_WALKING, FISH_FROG_MAN_ATTACK, LIZZARD_IDLE, LIZZARD_WALKING, LIZZARD_ATTACK, RAT_IDLE, RAT_WALKING, RAT_ATTACK, BLOB_IDLE, BLOB_WALKING, BLOB_ATTACK, GHOST_IDLE, GHOST_WALKING, GHOST_ATTACK,;

	private String getProperty() {
		Properties prop = new Properties();
		try {
			File f = new File(System.getProperty("user.dir"));
			f = new File(Const.RESSOURCES_FOLDER + "animationNames.properties");
			prop.load(new FileInputStream(f));
		} catch (Exception e) {
			e.printStackTrace();
		}
		return prop.getProperty(this.name());
	}

	public String getFileName() {
		return getProperty();
	}
}
